2023-02-20 09:47:54,065 - INFO - 
Config:
'add_train': True
'batch_size': 16
'cudadevice': 'cuda:1'
'cur_time': '2023_02_20_09_47_53'
'data_selected': ['B1']
'do_figure_save': True
'do_log_print_to_screen': True
'do_log_save_to_file': True
'do_predict': True
'do_predict_roll': False
'do_train': False
'do_train_visualized': False
'dropout_rate': 0.2
'dynamic_data_root': 'input/csv/dynamic'
'dynamic_length': 2
'embedding_size': 256
'epoch': 100
'feature_columns': [0, 1, 3]
'figure_save_path': 'result/figure/'
'hidden_size': 256
'humansize': 9
'input_size': 3
'label_columns': [3]
'label_in_feature_index': [2]
'learning_rate': 5e-05
'log_save_path': 'result/logs/2023_02_20_09_47_53_pytorch/'
'lstm_layers': 2
'model_name': '.pth'
'model_postfix': {'pytorch': '.pth'}
'model_save_path': 'result/model/'
'name': 'A1,C1_Attention_hc_True_RMLSE16_ds_fusion53'
'naturesize': 4
'only_dynamic': 0
'only_static_concat_dynamic': 0
'only_static_plus_dynamic': 0
'output_size': 1
'patience': 5
'predict_day': 3
'random_seed': 42
'roll_predict_day': 125
'shuffle_train_data': False
'static_data_path': 'input/csv/static/All_static.csv'
'static_human_column': [4, 5, 6, 7, 8, 9, 10, 11, 12]
'static_nature_column': [0, 1, 2, 3]
'time_step': 5
'train_data_rate': 0.1
'train_name': 'A1,C1'
'traindata': 'traindata'
'ttotrain': 0
'use_attention': True
'use_cuda': True
'use_static_embedding': True
'used_frame': 'pytorch'
'val_name': 'B1'
'valid_data_rate': 0.15
2023-02-20 09:48:03,721 - ERROR - Run Error
Traceback (most recent call last):
  File "full_system_no_dynamic.py", line 623, in main
    draw(config, data_gainer, logger, pred_result,'_no_roll')
  File "full_system_no_dynamic.py", line 565, in draw
    mse = mean_squared_error(calculate_label_data[:] , predict_data[:])
  File "/data/zhangyisi/anaconda3/envs/Shale/lib/python3.8/site-packages/sklearn/metrics/_regression.py", line 442, in mean_squared_error
    y_type, y_true, y_pred, multioutput = _check_reg_targets(
  File "/data/zhangyisi/anaconda3/envs/Shale/lib/python3.8/site-packages/sklearn/metrics/_regression.py", line 100, in _check_reg_targets
    check_consistent_length(y_true, y_pred)
  File "/data/zhangyisi/anaconda3/envs/Shale/lib/python3.8/site-packages/sklearn/utils/validation.py", line 387, in check_consistent_length
    raise ValueError(
ValueError: Found input variables with inconsistent numbers of samples: [341, 342]
