2023-02-26 19:37:11,856 - INFO - 
Config:
'add_train': True
'batch_size': 16
'cudadevice': 'cuda:1'
'cur_time': '2023_02_26_19_37_10'
'data_cache_path': 'cache'
'data_selected': ['C1']
'do_figure_save': True
'do_log_print_to_screen': True
'do_log_save_to_file': True
'do_predict': True
'do_predict_roll': False
'do_train': False
'do_train_visualized': False
'dropout_rate': 0.2
'dynamic_data_root': 'input/csv/dynamic'
'dynamic_length': 2
'embedding_size': 256
'epoch': 100
'feature_columns': [0, 1, 3]
'figure_save_path': 'result/figure/'
'hidden_size': 256
'humansize': 9
'input_size': 3
'label_columns': [3]
'label_in_feature_index': [2]
'learning_rate': 5e-05
'log_save_path': 'result/logs/2023_02_26_19_37_10_pytorch/'
'lstm_layers': 2
'model_name': '.pth'
'model_postfix': {'pytorch': '.pth'}
'model_save_path': 'result/model/'
'name': 'A1_Attention_hc_True_RMLSE16_ds_fusion53'
'naturesize': 4
'only_dynamic': 0
'only_static_concat_dynamic': 0
'only_static_plus_dynamic': 0
'output_size': 1
'patience': 5
'predict_day': 3
'random_seed': 42
'roll_predict_day': 125
'save_data_cache': True
'shuffle_train_data': False
'static_data_path': 'input/csv/static/All_static.csv'
'static_human_column': [4, 5, 6, 7, 8, 9, 10, 11, 12]
'static_nature_column': [0, 1, 2, 3]
'time_step': 5
'train_data_rate': 0.1
'train_name': 'A1'
'traindata': 'traindata'
'ttotrain': 0
'use_attention': True
'use_cuda': True
'use_static_embedding': True
'used_frame': 'pytorch'
'val_name': 'C1'
'valid_data_rate': 0.15
2023-02-26 19:37:14,717 - ERROR - Run Error
Traceback (most recent call last):
  File "/data/zhangyisi/ShaleOil_latest/full_system_no_dynamic.py", line 649, in main
    pred_result = predict(config, encoder_test, human, nature)       # 这里输出的是未还原的归一化预测数据
  File "/data/zhangyisi/ShaleOil_latest/full_system_no_dynamic.py", line 453, in predict
    model.load_state_dict(torch.load(config.model_save_path +config.name+ config.model_name))   # 加载模型参数
  File "/data/zhangyisi/anaconda3/envs/Shale/lib/python3.8/site-packages/torch/serialization.py", line 594, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/data/zhangyisi/anaconda3/envs/Shale/lib/python3.8/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/data/zhangyisi/anaconda3/envs/Shale/lib/python3.8/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'result/model/A1_Attention_hc_True_RMLSE16_ds_fusion53.pth'
